from typing import Protocol

from modele_lignes import LigneExploitation


class DAOLigne(Protocol):
    """Contrat de persistance à implémenter avec PostgreSQL."""

    def creer(self, ligne: LigneExploitation) -> LigneExploitation: ...
    def trouver_par_id(self, ligne_id: int) -> LigneExploitation | None: ...
    def lister(self) -> list[LigneExploitation]: ...
    def modifier(self, ligne: LigneExploitation) -> LigneExploitation: ...
    def supprimer(self, ligne_id: int) -> None: ...
